FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/worker ./cmd/worker

FROM grafana/k6:latest
USER root
COPY --from=build /out/worker /usr/local/bin/worker
ENV K6_PATH=k6
ENTRYPOINT ["worker"]
